/** All user-facing copy (pt-BR, as in the design mockup). Kept in one place so a later i18n pass has one file to touch. */
export const t = {
  appName: 'Bancada',
  sessionsTitle: 'Sessões',
  sessionsSummary: (total: number, running: number): string =>
    total === 0
      ? 'Nenhuma sessão aberta'
      : `${total} ${total === 1 ? 'sessão' : 'sessões'} · ${running} ${running === 1 ? 'ativa' : 'ativas'}`,
  noSessions: 'Abra um terminal no Bancada no Mac e ele aparece aqui.',
  running: 'ativa',
  exited: 'encerrada',
  lastActivity: (when: string): string => `última atividade ${when}`,
  noActivity: 'sem atividade ainda',
  back: 'Sessões',
  backLabel: 'Voltar para as sessões',
  pairTitle: 'Parear este aparelho',
  pairIntro: 'No Mac, rode "pnpm --filter @bancada/server pair" e digite o código que aparece.',
  pairCode: 'Código de pareamento',
  pairName: 'Nome do aparelho',
  pairSubmit: 'Parear',
  pairing: 'Pareando…',
  pairInvalid: 'Código inválido ou expirado. Gere outro no Mac.',
  pairRateLimited: (seconds: number): string => `Muitas tentativas. Tente de novo em ${seconds} s.`,
  pairNetwork: 'Sem conexão com o servidor. Confira o Tailscale.',
  pairInstallHint:
    'Para receber notificações, o Bancada precisa estar instalado: toque em Compartilhar, depois em "Adicionar à Tela de Início", abra o app pelo ícone e pareie por lá.',
  offline: 'Sem conexão com o servidor',
  offlineHint: 'Confira se o Tailscale está ligado e se o Bancada está aberto no Mac.',
  retry: 'Tentar de novo',
  hostDown: 'O Bancada no Mac não está respondendo.',
  notificationsTitle: 'Notificações',
  notificationsEnable: 'Ativar notificações',
  notificationsEnabling: 'Ativando…',
  notificationsOn: 'Notificações ativas neste aparelho',
  notificationsDisable: 'Desativar',
  notificationsInstallFirst:
    'No iPhone as notificações só funcionam depois de "Adicionar à Tela de Início" (Compartilhar, depois Adicionar à Tela de Início). Abra o Bancada pelo ícone e volte aqui.',
  notificationsExplain: 'Você recebe um aviso quando um terminal toca o sino (BEL), mesmo com o celular bloqueado.',
  notificationsDenied: 'As notificações estão bloqueadas. Libere em Ajustes, Notificações, Bancada.',
  notificationsUnsupported: 'Este navegador não suporta notificações push.',
  notificationsFailed: 'Não deu para ativar as notificações. Tente de novo.',
  signOut: 'Sair deste aparelho',
  signOutConfirm: 'Desparear este aparelho? Será preciso um novo código para voltar.',
  keysLabel: 'Teclas rápidas',
  inputLabel: 'Responder ao agente',
  inputPlaceholder: 'Responder ao agente',
  send: 'Enviar resposta',
  connecting: 'Conectando…',
  reconnecting: 'Reconectando…',
  live: 'ao vivo',
  sessionEnded: 'Sessão encerrada',
  sessionNotFound: 'Essa sessão não existe mais.',
  readOnlySize: (cols: number, rows: number): string => `${cols}×${rows}`,
} as const
