import os from 'node:os'
import type { CpuByRole, LatencyStats } from './measure.js'

/** Pass bar for the default config, at replay speed 1 (docs/ROADMAP.md, proof a). */
export const PASS_BAR = { echoP95Ms: 50, droppedFramesPct: 5 } as const

export interface RunSpec {
  name: string
  label: string
  mode: 'all-webgl' | 'all-dom' | 'hybrid'
  /** WebGL slots (focused terminal included). */
  webglLimit: number
  speed: number
}

export interface RunResult {
  spec: RunSpec
  seconds: number
  latency: LatencyStats
  echoMissed: number
  frames: {
    total: number
    dropped: number
    droppedPct: number
    medianDelta: number
    p95Delta: number
    maxDelta: number
  }
  cpu: CpuByRole
  /** pty-host process, percent of one core. */
  hostCpu: number
  /** The sessions' own processes (the players and the echo program), percent of one core. */
  sessionsCpu: number
  renderers: { webgl: number; dom: number; contextLoss: number; unsupported: number }
  versions?: { electron: string; chrome: string }
}

export function passes(result: RunResult): boolean {
  return result.latency.p95 <= PASS_BAR.echoP95Ms && result.frames.droppedPct <= PASS_BAR.droppedFramesPct
}

const appCpu = (r: RunResult): number => r.cpu.renderer + r.cpu.gpu + r.cpu.main

/** CPU differences below this (percentage points of one core) are run-to-run noise on a shared machine. */
const CPU_NOISE = 0.5

/**
 * Among the hybrid configs that pass the bar, the one that costs the least CPU (renderer + GPU + main); CPU within the
 * noise counts as equal and the smaller WebGL budget wins (fewer contexts, less GPU memory). "All WebGL" is not
 * eligible: the board has no cap on terminals and Chromium keeps about 16 contexts per page, so it would start losing
 * contexts at the 17th terminal whatever the 16-terminal grid shows. "All DOM" is not the default either: this load is
 * too light to tell the renderers apart, and WebGL is what keeps the focused terminals smooth under heavier output.
 */
export function chooseDefault(results: RunResult[]): RunResult | null {
  const passing = results.filter((r) => passes(r) && r.spec.mode === 'hybrid')
  if (passing.length === 0) return null
  const lowest = Math.min(...passing.map(appCpu))
  return [...passing]
    .filter((r) => appCpu(r) <= lowest + CPU_NOISE)
    .sort((a, b) => a.spec.webglLimit - b.spec.webglLimit)[0] as RunResult
}

const f = (value: number, digits = 1): string => value.toFixed(digits)

function resultTable(results: RunResult[]): string {
  const rows = results.map((r) =>
    [
      r.spec.label,
      `${f(r.latency.p50)} / ${f(r.latency.p95)} / ${f(r.latency.p99)}`,
      f(r.latency.max),
      `${r.latency.n} (${r.echoMissed})`,
      `${f(r.frames.droppedPct, 2)}% (${r.frames.dropped} of ${r.frames.total})`,
      `${f(r.frames.medianDelta)} / ${f(r.frames.p95Delta)} / ${f(r.frames.maxDelta)}`,
      passes(r) ? 'pass' : 'FAIL',
    ].join(' | '),
  )
  return [
    '| config | echo p50 / p95 / p99 (ms) | echo max (ms) | keys (missed) | dropped frames | frame delta median / p95 / max (ms) | bar |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row} |`),
  ].join('\n')
}

function cpuTable(results: RunResult[]): string {
  const rows = results.map((r) =>
    [
      r.spec.label,
      f(r.cpu.renderer),
      f(r.cpu.gpu),
      f(r.cpu.main),
      f(r.cpu.other),
      f(r.hostCpu),
      f(r.sessionsCpu),
      `${r.renderers.webgl} / ${r.renderers.dom}`,
      String(r.renderers.contextLoss),
    ].join(' | '),
  )
  return [
    '| config | renderer % | GPU % | main % | other Electron % | pty-host % | session processes % | WebGL / DOM terminals | WebGL context losses |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- |',
    ...rows.map((row) => `| ${row} |`),
  ].join('\n')
}

export interface ReportInput {
  results: RunResult[]
  best: RunResult | null
  stress: RunResult | null
  privateFixture: boolean
  windowSeconds: number
}

export async function renderReport({
  results,
  best,
  stress,
  privateFixture,
  windowSeconds,
}: ReportInput): Promise<string> {
  const versions = results.find((r) => r.versions)?.versions
  const cpus = os.cpus()
  const lines: string[] = []
  lines.push('# F0-a: sixteen terminals with continuous agent-like output')
  lines.push('')
  lines.push('Generated by `pnpm --filter @bancada/desktop bench`.')
  lines.push('')
  lines.push(`- Date: ${new Date().toISOString()}`)
  lines.push(
    `- Machine: ${os.type()} ${os.release()} ${os.arch()}, ${cpus[0]?.model ?? 'unknown CPU'}, ${cpus.length} cores, ${Math.round(os.totalmem() / 2 ** 30)} GiB`,
  )
  if (versions) lines.push(`- Runtime: Electron ${versions.electron} (Chromium ${versions.chrome})`)
  lines.push(
    '- Window: 1512x982 content size, 4x4 grid, each terminal 60x12 cells (about 378x209 px under a 36 px header)',
  )
  lines.push(
    privateFixture
      ? '- Replay: private fixture `claude-session-1.cast` (a real Claude Code session, not committed), speed 1, `--loop`'
      : '- Replay: the private fixture `claude-session-1.cast` was missing, so the committed synthetic `tools/replay/fixtures/synthetic/agent-like.cast` was used (speed 1, `--loop`)',
  )
  lines.push(
    '- Terminals: 15 run the replay player, 1 runs a raw-mode echo program (`apps/desktop/bench/echo.cjs`) and has the keyboard focus',
  )
  lines.push(`- Each run: ${windowSeconds} s measured after 8 s of warm-up, a fresh app and a fresh pty-host per run`)
  lines.push('')
  lines.push('## Method')
  lines.push('')
  lines.push(
    "- **Echo latency.** A real key press (`page.keyboard.press`, Chromium input events) on the focused terminal. The clock starts in a capture-phase `keydown` listener on the terminal's input element, which is the moment the key is dispatched in the renderer, and stops in the first `requestAnimationFrame` after xterm's `onWriteParsed` reports that the echoed glyph is the character before the cursor. xterm schedules its own paint in `requestAnimationFrame` too, so that callback runs after the paint call of the same frame (for WebGL, the draw call; the compositor is not included). One key every 80 ms or so, a new letter each time; a key whose echo did not show within 1 s counts as missed.",
  )
  lines.push(
    "- **Dropped frames.** A `requestAnimationFrame` loop over the whole window; a delta above 2 x 16.7 ms (33.3 ms) is a dropped frame, reported as a share of all frames. The median delta shows the display's refresh (8.3 ms is a 120 Hz panel).",
  )
  lines.push(
    '- **CPU.** Renderer, GPU and main come from `app.getAppMetrics()` (`percentCPUUsage`, sampled every second, averaged; 100 is one core). The pty-host and the session processes come from `ps -o time=` deltas over the window (macOS `ps %cpu` is a decaying average, so it is not used). The session processes are the replay players and the echo program: load that exists with any terminal app.',
  )
  lines.push(
    '- **WebGL budget.** `hybrid` gives WebGL to the focused terminal and the most recently active ones, N slots in total; the other terminals use the DOM renderer. A context loss falls back to the DOM renderer and is counted.',
  )
  lines.push('')
  lines.push('## Renderer configs at replay speed 1')
  lines.push('')
  lines.push(resultTable(results))
  lines.push('')
  lines.push(cpuTable(results))
  lines.push('')
  lines.push(
    `Pass bar for the default config: echo p95 <= ${PASS_BAR.echoP95Ms} ms and dropped frames <= ${PASS_BAR.droppedFramesPct}% at speed 1.`,
  )
  lines.push('')
  lines.push('## Default')
  lines.push('')
  if (best) {
    lines.push(
      `**${best.spec.label}** is the default: it passes the bar (echo p95 ${f(best.latency.p95)} ms, ${f(best.frames.droppedPct, 2)}% dropped frames) with app CPU within noise of the lowest among the hybrid configs that pass (${f(appCpu(best))}% of a core across renderer, GPU and main), and the smallest WebGL budget among those. "All WebGL" is not eligible: the board has no cap on terminals and Chromium keeps about 16 WebGL contexts per page, so it would start losing contexts at the 17th terminal even though the 16-terminal grid shows none. "All DOM" is not the default because this load is too light to tell the renderers apart and WebGL is what keeps the focused terminals smooth under heavier output.`,
    )
    lines.push('')
    lines.push(
      'Read the tables with the load in mind: the recorded agent session averages about 0.5 KB/s per terminal (peaks near 12 KB/s), so 16 terminals are well inside what any renderer handles, and the differences between configs are within run-to-run noise (the machine was shared). What the bench settles is that every config clears the bar by a wide margin, that 16 WebGL contexts at once did not lose a context here, and that a hybrid budget costs nothing measurable, which is why the default keeps WebGL for a few terminals and bounds the number of contexts.',
    )
    lines.push('')
    lines.push(
      best.spec.mode === 'hybrid'
        ? `The WebGL budget N is **${best.spec.webglLimit}** (\`DEFAULT_WEBGL_LIMIT\` in \`packages/ui/src/terminal/webgl-budget.ts\`).`
        : best.spec.mode === 'all-dom'
          ? 'The WebGL budget N is **0**: the DOM renderer everywhere.'
          : 'The WebGL budget N is **unlimited** (16 contexts in this grid).',
    )
  } else {
    lines.push(
      '**No eligible config passes the bar.** See the tables above; the default stays at the hybrid 4 until this is understood.',
    )
  }
  lines.push('')
  if (stress) {
    lines.push('## Stress: replay speed 4')
    lines.push('')
    lines.push(
      `Same grid with the best config (${best?.spec.label ?? 'n/a'}) and the players running four times faster.`,
    )
    lines.push('')
    lines.push(resultTable([stress]))
    lines.push('')
    lines.push(cpuTable([stress]))
    lines.push('')
    lines.push(
      `The pass bar applies at speed 1; at speed 4 the run is ${passes(stress) ? 'still inside it' : 'outside it'} (echo p95 ${f(stress.latency.p95)} ms, ${f(stress.frames.droppedPct, 2)}% dropped frames).`,
    )
    lines.push('')
  }
  lines.push('## Not done')
  lines.push('')
  lines.push("Comparison with Orca not done: it would load the user's live Orca, which runs his agents.")
  lines.push('')
  lines.push('## Reproduce')
  lines.push('')
  lines.push('```sh')
  lines.push(
    'pnpm --filter @bancada/desktop bench   # builds pty-host, replay and the app, opens a 1512x982 window for about 8 minutes',
  )
  lines.push('```')
  lines.push('')
  lines.push(
    '`BANCADA_BENCH_ONLY=all-dom,hybrid-4` runs a subset and prints the report instead of writing it; `BANCADA_BENCH_SECONDS=20` shortens the window.',
  )
  lines.push('')
  return lines.join('\n')
}
